name: Recorder
options:
  deploymentTarget:
    iOS: "15.0"
    macOS: "12.0"
  createIntermediateGroups: true
targets:
  Recorder iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources/Recorder
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.recorder.ios
        TARGETED_DEVICE_FAMILY: 2   # iPad only
        INFOPLIST_FILE: Resources/Info.iOS.plist
  Recorder macOS:
    type: application
    platform: macOS
    sources:
      - path: Sources/Recorder
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.recorder.macos
        INFOPLIST_FILE: Resources/Info.macOS.plist